<?php

use Drupal\block\Entity\Block;
use Drupal\media\Entity\Media;
use Drupal\file\Entity\File;

function webspark_isearch_theme_suggestions_block_alter(array &$suggestions, array $variables) {
  if (isset($variables['elements']['content']['#block_content'])){
    $blockType = $variables['elements']['content']['#block_content']->bundle();
    if ($blockType == 'isearch') {
      $suggestions[] = 'block__' . 'isearch';
    }
  }
}


/**
 * Implements hook_preprocess_block().
 */
function webspark_isearch_preprocess_block(&$variables) {
  $block = Block::load($variables['elements']['#id']);
  if (isset($variables['elements']['content']['#block_content'])){
    $blockType = $variables['elements']['content']['#block_content']->bundle();
    if ($blockType == "isearch") {
      $content = $variables['elements']['content'];
      $ids        = $content['field_ids']['#items']->get(0)->value;
      $sids       = $content['field_source_ids']['#items']->get(0)->value;
      $display    = $content['field_display_type']['#items']->get(0)->value;
      $showBio    = $content['field_show_bio']['#items']->get(0)->value;
      $showEmail  = $content['field_show_email']['#items']->get(0)->value;
      $showPhone  = $content['field_show_phone']['#items']->get(0)->value;
      $showPhoto  = $content['field_show_photo']['#items']->get(0)->value;
      $showTitle  = $content['field_show_title']['#items']->get(0)->value;
      if ($content['field_media']['#items']) {
        $image      = array_shift($content['field_media']['#items']->getValue());
      }
      $file = File::load($image['target_id']);
      $uri = $file->getFileUri();
      $imageurl = file_create_url($uri);
      $variables['isearch_display'] = $display;
      $variables['isearch_image'] = $imageurl;
      $variables['isearch_ids'] = $ids;
      $variables['isearch_source_ids'] = $sids;
      $variables['isearch_show_bio'] = $showBio;
      $variables['isearch_show_email'] = $showEmail;
      $variables['isearch_show_phone'] = $showPhone;
      $variables['isearch_show_photo'] = $showPhoto;
      $variables['isearch_show_title'] = $showTitle;
    }
  }
}